spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: EduCloud
  datasource:
    url: jdbc:sqlserver://localhost:1434;databaseName=EduCloud_db;encrypt=false
    username: MSI
    password: 1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      data-source-properties:
        sendStringParametersAsUnicode: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
server:
  port: 8080
  servlet:
    context-path: /api/v1/eduCloud


jwt:
  singerKey: ${JWT_SIGNER_KEY}
  valid-duration: 3600 # in second
  refreshable-duration: 360000 # in second


#cloud:
#  aws:
##    credentials:
##      accessKey: ${AWS_ACCESS_KEY_ID}
##      secretKey: ${AWS_SECRET_ACCESS_KEY}
#    region:
#      static: ${AWS_REGION}
#    bucket-name: ${AWS_S3_BUCKET_NAME}

cloud:
  aws:
    region:
      static: ${AWS_REGION:us-east-1}
    bucket-name: ${AWS_S3_BUCKET_NAME:educloud-storage-2026}